version: '3'

services:
  autoagent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
    environment:
      - PYTHONUNBUFFERED=1
      - GITHUB_AI_TOKEN=${GITHUB_AI_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
    networks:
      - autoagent-network

  web_ui:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8080:5000"
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=web_wrapper.py
      - GITHUB_AI_TOKEN=${GITHUB_AI_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
    depends_on:
      - autoagent
    networks:
      - autoagent-network

volumes:
  pip-cache:

networks:
  autoagent-network:
    driver: bridge